[package]
name = "container-create"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hostname = { version = "0.3.1", features = ["set"] }
libc = "0.2.151"
once_cell = "1.19.0"
